2025-02-23 19:12:50
training MLP from SCAN_NB15_CIC_os
2025-02-23 19:12:53
training SVM from SCAN_NB15_CIC_os
2025-02-23 19:12:53
Something went wrong with SVM from SCAN_NB15_CIC_os

All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\svm\_classes.py", line 317, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
                                           ^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\svm\_base.py", line 1173, in _fit_liblinear
    raise ValueError(
ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 1


2025-02-23 19:12:53
training XGB from SCAN_NB15_CIC_os
2025-02-23 19:12:53
Something went wrong with XGB from SCAN_NB15_CIC_os

All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\xgboost\core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\xgboost\sklearn.py", line 1559, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]


2025-02-23 19:12:53
training NB from SCAN_NB15_CIC_os
2025-02-23 19:12:53
training LR from SCAN_NB15_CIC_os
2025-02-23 19:12:53
Something went wrong with LR from SCAN_NB15_CIC_os

All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1301, in fit
    raise ValueError(
ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 1


2025-02-23 19:12:53
training DT from SCAN_NB15_CIC_os
2025-02-23 19:12:54
Done!
2025-02-23 21:26:58
training MLP from SCAN_NB15_CIC_os
2025-02-23 21:27:00
training SVM from SCAN_NB15_CIC_os
2025-02-23 21:27:00
Something went wrong with SVM from SCAN_NB15_CIC_os

All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\svm\_classes.py", line 317, in fit
    self.coef_, self.intercept_, n_iter_ = _fit_liblinear(
                                           ^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\svm\_base.py", line 1173, in _fit_liblinear
    raise ValueError(
ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 1


2025-02-23 21:27:00
training XGB from SCAN_NB15_CIC_os
2025-02-23 21:27:01
Something went wrong with XGB from SCAN_NB15_CIC_os

All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\xgboost\core.py", line 726, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\xgboost\sklearn.py", line 1559, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0], got [1]


2025-02-23 21:27:01
training NB from SCAN_NB15_CIC_os
2025-02-23 21:27:01
training LR from SCAN_NB15_CIC_os
2025-02-23 21:27:01
Something went wrong with LR from SCAN_NB15_CIC_os

All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\anaconda3\envs\tf\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1301, in fit
    raise ValueError(
ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 1


2025-02-23 21:27:01
training DT from SCAN_NB15_CIC_os
2025-02-23 21:27:01
Done!
